### ISSUE TITLE
Standalone Version of AppIconExtractor.py

### ISSUE THREAD

**Issue by uurazzle** [autopkg/haircut-recipes#26]
Hi:

Thanks for sharing your AutoPkg processors with the community.

It would be nice to have a standalone version of `AppIconExtractor.py` that isn't dependent on AutoPkg and could be used outside it for other workflows or if you aren't using AutoPkg. Or community AutoPkg processors like [jamf-upload](https://github.com/grahampugh/jamf-upload) have made standalone versions available for similar reasons.

**Comment by haircut** [comment]
Thanks for this request @uurazzle and apologies for the delay.

I don't have plans to implement standalone scripts. The use case here is exclusively for automation within AutoPkg, as I think there are better options like [SAP Icons](https://github.com/SAP/macos-icon-generator) for non-programmatic use cases.

**Comment by uurazzle** [comment]
Hi @haircut, 

Thanks for added the standalone support, SAP Icons is lacking similar support, I put a feature request in. You could implement this standalone with tools like munkipkg and other automation outside just AutoPkg too.
