### ISSUE TITLE
Hudl Sportscode fails to download | URLTextSearcher: Error: No match found on URL Hudl Sportscode recipe

### ISSUE THREAD

**Issue by moritz-Z** [autopkg/haircut-recipes#44]
Hudl Sportscode fails to download | URLTextSearcher: Error: No match found on URL Hudl Sportscode recipe

When running the Hudl Sportscode recipe I'm getting the following error.

Error in HudlSportscode.download.recipe: Processor: URLTextSearcher: Error: No match found on URL: 

It looks like the url is a new one for Version 12.47.0
New URL: https://sportscode64-updates.s3.us-east-1.amazonaws.com/PublicReleaseDmgs/HudlSportscode-12.47.0.dmg.zip

please update the re_pattern.
for example this resolve the download issue for me:
`<key>re_pattern</key>
                <string>href="(https:\/\/(((hudl-content|sportsxcode64-updates).s3|sportscode64-updates.s3.us-east-1).amazonaws.com|static.hudl.com)\/(craft\/elite\/downloads|PublicReleaseDmgs)\/[Hh]udl[Ss]portscode([\.\-\_]?\d+?[\.\-\_]?\d+?[\.\-\_]?\d+?|)\.dmg(\.zip|)(\?mtime=.*?)?)"</string>`

**Comment by haircut** [comment]
Please see https://github.com/autopkg/primalcurve-recipes/tree/master/Hudl for the maintained recipes for this vendor. I no longer maintain them, and they are marked deprecated.
