### ISSUE TITLE
MakeMKV Duplicate Recipes

### ISSUE THREAD

**Issue by apizz** [autopkg/haircut-recipes#8]
Hi, there. Per https://macadmins.slack.com/archives/C056155B4/p1580839875339200, wanted to address our duplicate MakeMKV download recipes.

Given it appears you created your recipes after me (https://gist.github.com/homebysix/7b2800c1d7494649a14a0f18cb62926c#file-2020-02-04-autopkg-dupe-recipe-filenames-txt-L314) it appears that may have been because my download recipe created a DMG.

I've subsequently updated my download recipe to not do that and have moved that step to my munki recipe.  If that addresses your need, I don't think you need your own download recipe anymore and can just update the parent recipe info on your pkg recipe.  Let me know what you think.

**Comment by apizz** [comment]
👋

**Comment by haircut** [comment]
Apologies for the long delay; I'd missed this issue.

Commit fb473b7 updates my `.pkg` recipe to use your parent `.download` recipe, and adds `DeprecationWarning` to my `.download` recipe through 2020-09-30. After that date my `.download` recipe will be removed.

Thanks for making the change to your `.download` recipe! 🎉

**Comment by apizz** [comment]
Better late than never!  Thank you.
